spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent-a-car
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    changelog: classpath:/db/changelog/master.yml
    enabled: true

